title: "Nathan Jessen's Presentations"
description: "A collection of technical presentations on CSS methodologies, Sass best practices, and modern web development techniques."
baseurl: /slides
url: "https://nathanjessen.github.io"
author: "Nathan Jessen"

include:
  - "_pages"

# Build settings
markdown: kramdown
